### ISSUE TITLE
Recreate the nav menu from a hamburger bar when in wide mode

### ISSUE THREAD

**Issue by SlamBamActionman** [GameMakersToolkit/team-finder#150]
It looks pretty wonky when you're on a computer ngl. If we could get it to be a proper menu of some kind for desktop (one that folds in from the side perhaps?) it would probably look a lot greater.

**Comment by Willdotwhite** [comment]
I, err, could do with some pointers on this one 😬 

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/13312237/171623124-c7a1da1f-4faa-40a7-ba22-a3c5444ca832.png">
