### ISSUE TITLE
Make PostModal not fugly as heck

### ISSUE THREAD

**Issue by Willdotwhite** [GameMakersToolkit/team-finder#163]
This could be betterer

<img width="885" alt="image" src="https://user-images.githubusercontent.com/13312237/171701848-14402f36-833d-44bf-be15-68dc603c84c8.png">

**Comment by jalexandremoreira** [comment]
If we're stuck with the modal being this specific size for some reason, I'd create a vertical flexbox around the whole thing with justifyContent="space-around", and make the top bit and the button be 2 different divs.

This would make the button stick to the bottom no matter the size of the description. Everything else looks okay to me, without going into super redesign mode
