### ISSUE TITLE
No forced wrapping for descriptions on Mobile

### ISSUE THREAD

**Issue by GGreenHeart** [GameMakersToolkit/team-finder#198]
If someone's description has a single piece of unbroken text that's absurdly long, well, it shows up exactly like that on the homepage:

![Screenshot_20220615-114700_Chrome](https://user-images.githubusercontent.com/93684089/173870498-f251420d-f0fd-49e0-8aaa-42d9e23596e0.png)

**Comment by Willdotwhite** [comment]
Will be fixed by #200
