### ISSUE TITLE
Change redirect link after generating the JWT to a frontend endpoint

### ISSUE THREAD

**Issue by awildbrysen** [GameMakersToolkit/team-finder#7]

**Comment by Willdotwhite** [comment]
This will be made slightly neater after #19, as the API currently doesn't know how to redirect back to the UI

**Comment by Willdotwhite** [comment]
After #19 is merged, #21 will be ready to merge to complete the redirect journey

**Comment by Willdotwhite** [comment]
Fixed by #21
