### ISSUE TITLE
More filters for Home page

### ISSUE THREAD

**Issue by dallonf** [GameMakersToolkit/team-finder#87]
TODO: list of filterable fields

**Comment by Willdotwhite** [comment]
Currently in place:
- Description
- Skills possessed
- Skills sought
- Preferred tools

Potential additions:
- Availability
- Timezone
- Languages

**Comment by Willdotwhite** [comment]
Other potential search tools:
- Order by created/updated

**Comment by Willdotwhite** [comment]
Languages added in #115

**Comment by Willdotwhite** [comment]
Timezones added in #120

**Comment by Willdotwhite** [comment]
Order By filters will be another task
