### ISSUE TITLE
Finish My Post form

### ISSUE THREAD

**Issue by dallonf** [GameMakersToolkit/team-finder#88]
Needs to support all the fields that the API supports

**Comment by Willdotwhite** [comment]
Fields already present:
- title
- description
- skillsPossessed
- skillsSought
- preferredTools
- availability

Remaining fields:
- timezoneStr
- languages

**Comment by Willdotwhite** [comment]
Languages will be added in #115

**Comment by Willdotwhite** [comment]
Timezones will be added in #120
